### ISSUE TITLE
How to determine what is a file and what's a directory?

### ISSUE THREAD

**Issue by icidasset** [gren-lang/node#3]
Currently this can be done by recovering from an error, see https://github.com/icidasset/shikensu-gren/blob/e44d3928a90faa4a0017eaaa4894d0c771332867/src/Shikensu.gren#L60-L62 for an example.

But it would be great to have a better way of doing this.
And perhaps even have the info handy directly when listing a directory.

**Comment by robinheghan** [comment]
Would #6 solve this issue for you, @icidasset ?

**Comment by icidasset** [comment]
@robinheghan Perfect 👌
