### ISSUE TITLE
Add a function to get the absolute path of the current working directory

### ISSUE THREAD

**Issue by icidasset** [gren-lang/node#4]
Or the absolute path of any item.

**Comment by robinheghan** [comment]
I've added a few functions on `main` to address this issue: https://github.com/gren-lang/node/blob/63d0e0718abae7fcb019fef58984edcc7b3142b4/src/FileSystem.gren#L318

Does this meet the use case that you have?

**Comment by icidasset** [comment]
@robinheghan Yup, that's great, thank you!
